### PR TITLE
Fix usage instructions in README

### PR DESCRIPTION
**Pull request by tinexw**

### CODE REVIEW

**Review by melnychukvitaliy — APPROVED** [review]

**Comment by melnychukvitaliy** [comment]
@tinexw Thanks for fixing it!

Did you have any others issues with action?

**Comment by tinexw** [comment]
@melnychukvitaliy actually yes, but I didn't investigate further because I didn't know if it was because of my setup or because of the action.

The error I got was
```
(node:1921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'number' of undefined
    at getChangedFiles (/home/runner/work/_actions/barecheck/code-coverage-action/v0.3.3/dist/index.js:6380:56)
    at showAnnotations (/home/runner/work/_actions/barecheck/code-coverage-action/v0.3.3/dist/index.js:6149:32)
    at runFeatures (/home/runner/work/_actions/barecheck/code-coverage-action/v0.3.3/dist/index.js:6747:9)
    at async runCodeCoverage (/home/runner/work/_actions/barecheck/code-coverage-action/v0.3.3/dist/index.js:6766:3)
    at async main (/home/runner/work/_actions/barecheck/code-coverage-action/v0.3.3/dist/index.js:6783:3)
(node:1921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by melnychukvitaliy** [comment]
@tinexw Can you also share your Github workflow configuration?

**Comment by melnychukvitaliy** [comment]
It might be relative to https://github.com/barecheck/code-coverage-action/issues/47. 

This action is only available with `pull_request` workflows events for now. I hope, we will have the support of push events as well in the near future

**Comment by tinexw** [comment]
I could no reproduce the error. It no longer shows but I still don't see any coverage information in my PR (I'm using both event types, `push`and `pull_request`). 
I was using a different action previously and it failed because the coverage report was too big. Could also be related. I can try to create a minimal example later to reproduce. If I manage I'll open a separate issue since it's not really related to this PR ;-)

**Comment by melnychukvitaliy** [comment]
@tinexw that's great, I am happy to help, let me know if you have any updates

**Pull request merged**
