### PR TITLE
Move to node16 from node12

### LINKED ISSUE #232: Node12 actions are deprecated
Hello!
I get messages in the logs of the actions:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/download-artifact@v2, barecheck/code-coverage-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Everything works, but such warning messages are annoying.

### PR DESCRIPTION
**Pull request by rvalitov**
Fixes #232

### CODE REVIEW

**Comment by rvalitov** [comment]
This PR assumes that you create a new release `barecheck/code-coverage-action@v2` after merging.

**Comment by vitaliimelnychuk** [comment]
Hey @rvalitov! Thanks for making this contribution!

Changes look good, is there a specific reason why we need `v2` version? If it's backward compatible with everything we already have I think we can keep `v1` without asking everyone to upgrade.

**Comment by rvalitov** [comment]
I followed the way how all other GitHub Actions repositories handled this situation. They released a new version. I'm not sure if there was some specific reason, because it's backward compatible. But are you sure you can rerelease an action without changing a version? I'm not sure about GitHub Actions, but some repositories do not allow to modify existing release, the only way is to make a new version. What do you think?

**Comment by vitaliimelnychuk** [comment]
What we have here, instead of the version we use the branch - Basically, all code updates inside the branch will be applied. Basically, if you just followed the docs and used:
```
- name: Generate Code Coverage report
  id: code-coverage
  uses: barecheck/code-coverage-action@v1
  with:
    barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
    lcov-file: "./coverage/lcov.info"
    base-lcov-file: "./coverage/base-lcov.info"
    send-summary-comment: true
    show-annotations: "warning"
 ```
   
Just by merging it will work, I just tested and changed seem fine so I am deploying this new version, try to just rerun action on your side and see if everything is fine ;)

**Review by vitaliimelnychuk — APPROVED** [review]

**Pull request merged**
